name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Build
  #        run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
      - name: Run library tests
        working-directory: ./library
        run: cargo test --verbose --package library
      - name: Run gui tests
        working-directory: ./gui
        run: cargo test --verbose --package gui --no-default-features